app:
  jwt:
    secret: "${APP_JWT_SECRET:this-is-my-development-secret-key-must-be-at-least-32-bytes-long}"
    expiration-minutes: "${APP_JWT_EXPIRATION_MINUTES:60}"
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
info:
  app:
    name: cinema-booking
    version: 0.0.1-SNAPSHOT
spring:
  application:
    name: cinema
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: cinema
    password: cinema
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"


