app:
  jwt:
    secret: "${APP_JWT_SECRET:this-is-my-development-secret-key-must-be-at-least-32-bytes-long}"
    expiration-minutes: "${APP_JWT_EXPIRATION_MINUTES:60}"
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
spring:
  application:
    name: cinema
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: cinema
    password: cinema
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
  flyway:
    enabled: true


